name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
          fetch-depth: 100

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v4.2

      - uses: marceloprado/has-changed-path@v1
        id: changed-a
        with:
          paths: a/

      - name: Test a
        if: steps.changed-a.outputs.changed == 'true'
        run: echo "Service a was updated"

      - uses: marceloprado/has-changed-path@v1
        id: changed-b
        with:
          paths: b/

      - name: Test b
        if: steps.changed-b.outputs.changed == 'true'
        run: exit 0

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying"

            