name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Hello world action step
        id: hello
        uses: rifhice/test-github-action@v10
        with:
          who-to-greet: 'Mona the Octocat'

      - uses: marceloprado/has-changed-path@v1
        id: changed-a
        with:
          paths: a/

      - name: Test a
        if: steps.changed-a.outputs.changed == 'true'
        run: echo "Service a was updated"

      - uses: marceloprado/has-changed-path@v1
        id: changed-b
        with:
          paths: b/

      - name: Test b
        if: steps.changed-b.outputs.changed == 'true'
        run: exit 1


      - name: Test c
        if: steps.changed-b.outputs.changed == 'true'
        run: exit 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying"

            