name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Hello world action step
        id: hello
        uses: rifhice/test-github-action@v42

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying"

            